services:
  products-ms:
    build:
      context: ./products-microservice
      dockerfile: Dockerfile
      target: dev
    command: npm run start:dev
    develop:
      watch:
        - path: ./products-microservice/src
          target: /usr/src/app/src
          action: sync
        - path: ./products-microservice/package.json
          target: /usr/src/app/package.json
          action: rebuild

  orders-ms:
    build:
      context: ./orders-microservice
      dockerfile: Dockerfile
      target: dev
    command: npm run start:dev
    develop:
      watch:
        - path: ./orders-microservice/src
          target: /usr/src/app/src
          action: sync
        - path: ./orders-microservice/package.json
          target: /usr/src/app/package.json
          action: rebuild

  payments-ms:
    build:
      context: ./payments-microservice
      dockerfile: Dockerfile
      target: dev
    command: npm run start:dev
    develop:
      watch:
        - path: ./payments-microservice/src
          target: /usr/src/app/src
          action: sync
        - path: ./payments-microservice/package.json
          target: /usr/src/app/package.json
          action: rebuild

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: Dockerfile
      target: dev
    command: npm run start:dev
    develop:
      watch:
        - path: ./client-gateway/src
          target: /usr/src/app/src
          action: sync
        - path: ./client-gateway/package.json
          target: /usr/src/app/package.json
          action: rebuild
