apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
  labels:
    app: auth-db
spec:
  serviceName: auth-db-headless
  replicas: 1

  selector:
    matchLabels:
      app: auth-db

  template:
    metadata:
      labels:
        app: auth-db

    spec:
      initContainers:
        - name: create-keyfile
          image: mongo:7.0.0
          command:
            - sh
            - -c
            - |
              if [ ! -f /data/db/keyfile ]; then
                openssl rand -base64 756 > /data/db/keyfile
              fi

              chmod 400 /data/db/keyfile
              chown 999:999 /data/db/keyfile
          volumeMounts:
            - name: data
              mountPath: /data/db

      containers:
        - name: mongodb
          image: mongo:7.0.0

          args:
            - mongod
            - --replSet
            - rs0
            - --keyFile
            - /data/db/keyfile
            - --bind_ip_all

          ports:
            - name: mongodb
              containerPort: 27017

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: mongo_user

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: mongo_password

            - name: MONGO_INITDB_DATABASE
              value: authdb

          startupProbe:
            tcpSocket:
              port: mongodb
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 36

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - >-
                  mongosh --host 127.0.0.1:27017
                  --username "$MONGO_INITDB_ROOT_USERNAME"
                  --password "$MONGO_INITDB_ROOT_PASSWORD"
                  --authenticationDatabase admin --quiet
                  --eval 'quit(db.hello().isWritablePrimary ? 0 : 1)'
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            tcpSocket:
              port: mongodb
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          volumeMounts:
            - name: data
              mountPath: /data/db

          resources: {}

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: auth-db-data
